### ISSUE TITLE
Name is already taken

### ISSUE THREAD

**Issue by lachlansneff** [phil-opp/bootloader#1]
It appears that the name **rustboot** is already taken. https://github.com/charliesome/rustboot

Might I suggest **boot.rs**?

**Comment by phil-opp** [comment]
Ah, thanks for the hint! One of the two hard things in computer science ^^.

I think I'll go with just “bootloader”. It's literal, not used by other rust tools, and plays nicely with the two other crates, “bootimage” and “bootinfo”.

**Comment by lachlansneff** [comment]
Awesome! 

It'd be great to have a single organization to consolidate tools and libraries for writing kernels in rust. I can donate the forge tool as well.
